import org.jetbrains.kotlin.backend.common.serialization.metadata.DynamicTypeDeserializer.id

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.30"
    id("org.jetbrains.kotlin.kapt") version "1.4.30"
    kotlin("plugin.serialization") version "1.4.30"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.4.30"
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

val kotlinVersion = "1.4.30"
val micronautVersion = "2.4.0"
val natsStreamingVersion = "2.2.3"
val vertxVersion = "4.0.3"
val crabzillaVersion = " 0.0.9-snapshot-4"
val kotlinSerializationVersion = "1.1.0"

allprojects {

    version = "0.1"
    group = "com.example1"

    repositories {
        mavenLocal()
        mavenCentral()
    }

    buildscript {
        repositories {
            mavenLocal()
            mavenCentral()
        }
    }

    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "org.jetbrains.kotlin.kapt")
    apply(plugin = "kotlinx-serialization")

//
//    plugins {
//        id("org.jetbrains.kotlin.jvm") version "1.4.30"
//        id("org.jetbrains.kotlin.kapt") version "1.4.30"
//        kotlin("plugin.serialization") version "1.4.30"
//        id("org.jetbrains.kotlin.plugin.allopen") version "1.4.30"
//        id("com.github.johnrengelman.shadow") version "6.1.0"
//    }


    dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
        implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
        implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinSerializationVersion")
        implementation(platform("io.vertx:vertx-stack-depchain:$vertxVersion"))
    }

    java {
        sourceCompatibility = JavaVersion.toVersion("11")
    }

    tasks {
        compileKotlin {
            kotlinOptions {
                jvmTarget = "11"
                freeCompilerArgs = listOf("-Xallow-result-return-type")
            }
        }
        compileTestKotlin {
            kotlinOptions {
                jvmTarget = "11"
                freeCompilerArgs = listOf("-Xallow-result-return-type")
            }
        }
    }
}

subprojects {

    repositories {
        mavenLocal()
        mavenCentral()
    }


    buildscript {
        repositories {
            mavenLocal()
            mavenCentral()
        }
    }

    apply(plugin = "org.jetbrains.kotlin.jvm")
    apply(plugin = "org.jetbrains.kotlin.kapt")
    apply(plugin = "kotlinx-serialization")

    ext {
        kotlinVersion
        micronautVersion
        natsStreamingVersion
        vertxVersion
        crabzillaVersion
        kotlinSerializationVersion
    }

    dependencies {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
        implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$kotlinSerializationVersion")
        implementation(platform("io.vertx:vertx-stack-depchain:$vertxVersion"))
    }
}