micronaut:
  application:
    name: example1-queries-handler
  server:
    port: 8084

#nats:
#  cluster-id: test-cluster
#  client-id: events-projector
#  user: al
#  password: alisson
#  host: localhost
#  port: 4222