micronaut:
  application:
    name: example1-events-publisher
  server:
    port: -1
  endpoints:
    all:
      enabled: true
      sensitive: false
    stop:
      enabled: false

nats:
  cluster-id: test-cluster
  client-id: events-publisher
  user: al
  password: alisson
  host: localhost
  port: 4222