micronaut:
  application:
    name: example1-events-projector
  server:
    port: -1

nats:
  cluster-id: test-cluster
  client-id: events-projector
  user: al
  password: alisson
  host: localhost
  port: 4222